# Generated by Django 4.1.3 on 2022-11-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=25)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('Address', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=25)),
                ('Contact', models.IntegerField()),
                ('School', models.CharField(max_length=20)),
                ('Section', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teq.courses')),
            ],
        ),
    ]
