# Generated by Django 4.1.3 on 2022-11-20 20:23

from django.db import migrations, models
import teq.models


class Migration(migrations.Migration):

    dependencies = [
        ('teq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlsInCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=200)),
                ('Picture', models.ImageField(upload_to=teq.models.get_path)),
            ],
        ),
        migrations.CreateModel(
            name='ItService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('IconService', models.ImageField(upload_to=teq.models.get_path)),
                ('Content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JuniorProgrammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=200)),
                ('Picture', models.ImageField(upload_to=teq.models.get_path)),
            ],
        ),
        migrations.CreateModel(
            name='TrainningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('Picture', models.ImageField(upload_to=teq.models.get_path)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
    ]
