# Generated by Django 4.1.3 on 2022-12-09 20:30

from django.db import migrations, models
import teq.models


class Migration(migrations.Migration):

    dependencies = [
        ('teq', '0002_girlsincode_itservice_juniorprogrammer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to=teq.models.get_path)),
            ],
        ),
        migrations.AlterField(
            model_name='girlsincode',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=teq.models.get_path),
        ),
        migrations.AlterField(
            model_name='itservice',
            name='IconService',
            field=models.ImageField(blank=True, null=True, upload_to=teq.models.get_path),
        ),
        migrations.AlterField(
            model_name='juniorprogrammer',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=teq.models.get_path),
        ),
        migrations.AlterField(
            model_name='trainningprogram',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=teq.models.get_path),
        ),
    ]
